### ISSUE TITLE
Don't bother with digest?

### ISSUE THREAD

**Issue by natevw** [danieldiekmeier/mini-style-loader#2]
Right now this returns the digest of the CSS source. In your README you discuss this but it doesn't look like you have much of a use case in mind for it? (There's even a "pretty pointless" comment in the example you do give…)

What do you think of dropping the digest "feature"? That would in turn let you drop the `loader-utils` require, leaving no dependencies in package.json — and this would then be a very simple/mini plugin indeed!

[This would be a breaking change, major revision bump if you're following semver.]

**Comment by danieldiekmeier** [comment]
Hey Nate,

what I meant in the README is that my example is pretty pointless – the feature itself is important for some of the projects I'm working an. I'm doing a lot of JS based A/B-testing, where I may have to add or remove the CSS on the fly.

I understand that the feature isn't necessary in a lot of cases, but in the cases that I do need it, it was very valuable to have.

Also, the overhead it adds is pretty small, especially after minification.

Thank you for taking the time to write about this, maybe I'll rethink this some time in the future. Until then, feel free to fork this repo and remove the digest! It's such a small amount of code, it should be easy to manage.

**Comment by natevw** [comment]
Makes sense, thanks for the clarification! Totally agree that the overhead it adds (i.e. to the output build product) is minimal, and the additional dependency on the dev/packaging server isn't worth worrying about if the feature is useful at times.
